[programs.devnet]
ayamegifsolana = "7fFqkK9ScNdwZnGoVhCBjc1zMynoiND95mcQWqr8tamR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/abuba/.config/solana/id.json"

[scripts]
test = "node tests/ayamegifsolana.js"

[test]
startup_wait = 10000